// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVMvTt_gLMMGtJXkrCUVOJzMGBQaWW8Z8',
    appId: '1:931475926490:web:83a6b87a5838f0f044e4e3',
    messagingSenderId: '931475926490',
    projectId: 'mynotes2nd-27eb8',
    authDomain: 'mynotes2nd-27eb8.firebaseapp.com',
    databaseURL: 'https://mynotes2nd-27eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mynotes2nd-27eb8.appspot.com',
    measurementId: 'G-RT0XB7NSL1',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCge1_YjTPJYU0f0cJtDpmP7s8ktZ0JDjQ',
    appId: '1:931475926490:android:dace002721500a8644e4e3',
    messagingSenderId: '931475926490',
    projectId: 'mynotes2nd-27eb8',
    databaseURL: 'https://mynotes2nd-27eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mynotes2nd-27eb8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyClyp0uOkAje19yNqS1u6fEPpRE-ee9N1Y',
    appId: '1:931475926490:ios:7ca9493eb5865e9944e4e3',
    messagingSenderId: '931475926490',
    projectId: 'mynotes2nd-27eb8',
    databaseURL: 'https://mynotes2nd-27eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mynotes2nd-27eb8.appspot.com',
    iosBundleId: 'com.ripu.mynotes',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyClyp0uOkAje19yNqS1u6fEPpRE-ee9N1Y',
    appId: '1:931475926490:ios:7ca9493eb5865e9944e4e3',
    messagingSenderId: '931475926490',
    projectId: 'mynotes2nd-27eb8',
    databaseURL: 'https://mynotes2nd-27eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mynotes2nd-27eb8.appspot.com',
    iosBundleId: 'com.ripu.mynotes',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAVMvTt_gLMMGtJXkrCUVOJzMGBQaWW8Z8',
    appId: '1:931475926490:web:c6b704d24fe59a3c44e4e3',
    messagingSenderId: '931475926490',
    projectId: 'mynotes2nd-27eb8',
    authDomain: 'mynotes2nd-27eb8.firebaseapp.com',
    databaseURL: 'https://mynotes2nd-27eb8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'mynotes2nd-27eb8.appspot.com',
    measurementId: 'G-64VEEYKRLS',
  );
}
